name: Build and Push Docker Image

on:
  push:
    branches: [ main, develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Set tag based on branch
        id: set_tag
        run: |
          if [[ $GITHUB_REF == 'refs/heads/main' ]]; then
            echo "TAG=latest" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == 'refs/heads/develop' ]]; then
            echo "TAG=develop" >> $GITHUB_ENV
          fi

      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/podimo:${{ env.TAG }}